"""Feature: add team table and fix password hashing

Revision ID: 7a00b8a7c8c9
Revises: 8a672e45d1a3
Create Date: 2025-12-19 15:04:34.112463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a00b8a7c8c9'
down_revision: Union[str, Sequence[str], None] = '8a672e45d1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
