"""Add Title to Meeting Model

Revision ID: a30a51572acf
Revises: bb8e7ed1ba41
Create Date: 2026-01-07 22:23:53.019540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a30a51572acf'
down_revision: Union[str, Sequence[str], None] = 'bb8e7ed1ba41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'title')
    # ### end Alembic commands ###
